tasks:
  - init: './scripts/Install.sh'
    command: 'echo "TODO: Replace with command to start project"'
  - command: 'cargo make serve'
  - command: 'cargo make watch'
ports:
  - port: 8000
    visibility: public
    onOpen: open-browser